apiVersion: v1
kind: Service
metadata:
  name: rota
  namespace: uat
  labels:
    app: rota
    environment: uat
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8484
  selector:
    app: rota

